---criando a tabela cliente2

CREATE TABLE "cliente2" (
  idCliente SERIAL PRIMARY KEY,
  nomeCliente varchar(100),
  sexo char(1),
  dataNascimento date,
  cidade varchar(100),
  email varchar(100)
);

INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (1,'Lionel Brown','M','2002-03-22','Ways','odio.a@erosProin.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (2,'Garrett Oconnor','M','1969-03-26','Carahue','Fusce.diam.nunc@sit.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (3,'Jelani Ballard','M','1980-04-21','Lanklaar','odio.Phasellus@nullaante.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (4,'Brendan Farrell','M','1964-09-07','Alert Bay','facilisis@ipsumDonec.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (5,'Denton Park','M','1995-10-13','Lowell','libero.et@iaculisnec.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (6,'Bruce Madden','M','1975-10-19','Camiña','urna.Nunc@ante.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (7,'Evan Francis','M','1968-10-22','Aisén','ultrices.a.auctor@est.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (8,'Carlos Browning','M','1999-04-17','Asigliano Veneto','pede.ac.urna@aliquetodio.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (9,'Dorian Haynes','M','1999-06-04','Incourt','nisi.a.odio@Aliquam.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (10,'Vaughan Jacobson','M','1973-05-03','İzmit','libero.nec@eutellus.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (11,'Carlos Dominguez','M','1963-05-13','Millport','id.nunc@ametultriciessem.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (12,'Hilel Sheppard','M','1972-06-22','Termini Imerese','libero.Morbi@Loremipsum.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (13,'Rajah Webster','M','2018-08-16','Noicattaro','magna.Praesent.interdum@acturpisegestas.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (14,'Deacon Graves','M','1976-07-27','Zierikzee','augue.eu.tellus@Inmipede.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (15,'Ashton George','M','1950-01-14','San Francisco','Curabitur@enimconsequatpurus.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (16,'Quentin Austin','M','2018-02-01','Graven Grez-Doiceau','erat.nonummy.ultricies@Aliquamtinciduntnunc.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (17,'Deacon Cook','M','1975-02-01','Heerhugowaard','ac@interdumNunc.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (18,'Dieter Ellis','M','1962-04-24','Erode','mollis.non.cursus@duiSuspendisseac.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (19,'Fitzgerald Alvarado','M','1951-08-16','Malartic','metus.eu.erat@facilisis.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (20,'Lars Bass','M','1992-09-16','Salon-de-Provence','enim@ante.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (21,'Abraham Lyons','M','1994-12-07','Hay-on-Wye','lacinia.orci.consectetuer@mattisIntegereu.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (22,'Cullen Burton','M','1954-02-08','Waasmunster','Lorem.ipsum@ultricesposuerecubilia.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (23,'Ralph Clark','M','1953-02-25','Montemesola','nulla@velitSedmalesuada.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (24,'Clayton Bean','M','1985-02-11','Cirencester','eu@egetdictum.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (25,'Aaron Gaines','M','1970-02-15','Oetingen','dapibus@elit.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (26,'Philip Rivera','M','1974-02-05','Barra do Corda','elit@liberoDonec.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (27,'Donovan Hooper','M','1977-01-27','Gravelbourg','ullamcorper.viverra@ultrices.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (28,'Zane Keith','M','1957-02-19','Monte San Savino','rhoncus.id@dolordolor.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (29,'Keane Prince','M','1995-06-11','San Costantino Calabro','Donec@sitamet.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (30,'Conan Contreras','M','1957-01-27','Bayswater','purus@loremauctor.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (31,'Mannix Flowers','M','2001-04-29','Minneapolis','nunc@Nuncuterat.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (32,'Xavier Kent','M','1964-08-28','Saskatoon','tellus.sem@tortor.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (33,'Evan Willis','M','1953-08-09','Welland','at@vulputate.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (34,'Len Frye','M','1990-09-02','South Bend','nunc@tristiquepharetraQuisque.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (35,'Benjamin Mcguire','M','1973-11-18','Norman Wells','Nulla.dignissim.Maecenas@vellectusCum.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (36,'Lev Frederick','M','1966-06-22','Norman','erat.vitae@Curabiturvel.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (37,'Ashton Weiss','M','1973-08-17','Meeffe','feugiat.nec.diam@Etiamligulatortor.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (38,'Hiram Hall','M','1961-08-25','Lens-Saint-Remy','mi.pede.nonummy@sapien.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (39,'Zahir Sosa','M','1972-04-09','Castelvecchio di Rocca Barbena','justo@Donec.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (40,'Ronan Mathews','M','1977-10-18','Kalisz','Vivamus.nisi@senectuset.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (41,'Arden Owen','M','2018-06-21','Wilhelmshaven','Suspendisse.tristique.neque@ante.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (42,'Lucas Freeman','M','1985-02-11','Parchim	City','tempor@Nunc.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (43,'Orlando Raymond','M','2005-06-11','Cajazeiras','purus.mauris.a@Morbi.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (44,'Brody Singleton','M','1959-05-31','Dereham','posuere.cubilia@NullamenimSed.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (45,'Chaney Ferguson','M','1994-03-02','Van','a.tortor.Nunc@molestieSedid.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (46,'Todd Russo','M','1993-09-17','Kingston','luctus.Curabitur@Nulla.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (47,'Jordan Travis','M','1984-02-12','Schwalbach','nunc.In@estacfacilisis.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (48,'Ezekiel May','M','1999-06-09','María Elena','faucibus.ut.nulla@sem.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (49,'Fritz Sims','M','2015-04-12','El Tabo','Phasellus@Integer.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (50,'Armando Barnett','M','1981-07-21','Hornsea','quam@arcu.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (51,'Zephania Crosby','M','2003-01-11','Aix-en-Provence','mauris.sit@laoreet.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (52,'Oscar Schroeder','M','1955-04-11','Hudson Bay','et.ipsum@iderat.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (53,'Elijah Blanchard','M','2001-10-21','Modena','lacinia.mattis.Integer@Integer.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (54,'Edward Moses','M','2014-12-27','Berbroek','sodales.Mauris.blandit@sapienNuncpulvinar.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (55,'Dalton Stanton','M','1981-05-02','Bremerhaven','elit.pretium@Morbimetus.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (56,'Jeremy Snyder','M','1991-07-18','Curanilahue','Suspendisse.tristique@ornareplacerat.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (57,'Zephania Fields','M','2016-01-21','Saint-Georges','sem.consequat.nec@nequeetnunc.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (58,'Tanek Peck','M','1984-09-15','Gisborne','Phasellus@temporerat.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (59,'Vincent Dorsey','M','1986-04-07','Kasur','ornare.lectus@egestasa.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (60,'Francis Holloway','M','1953-09-20','Yorkton','posuere.cubilia@Nam.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (61,'Cairo Bender','M','1973-06-20','Kapolei','vitae.dolor.Donec@elitpharetraut.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (62,'Luke Crawford','M','1998-02-21','Sellano','ipsum.porta.elit@ornare.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (63,'Ciaran Bonner','M','1985-03-26','Henderson','porttitor@enimcondimentum.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (64,'Amos Leach','M','2004-01-23','Saint Andr�','magnis@Naminterdum.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (65,'Benedict Waters','M','1956-06-02','Farrukhabad-cum-Fatehgarh','tincidunt@acmetusvitae.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (66,'Dennis Cabrera','M','1992-05-19','Castellafiume','In.lorem.Donec@egetlacusMauris.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (67,'Lev Ford','M','1954-11-14','Vergemoli','sed.est.Nunc@magna.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (68,'Dane Fields','M','2013-07-14','Kaster','Sed.molestie@scelerisque.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (69,'Vernon Jimenez','M','1977-07-24','Paglieta','Fusce@estNunclaoreet.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (70,'Avram French','M','2017-07-05','Siverek','luctus@urnaconvallis.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (71,'Keane Sanders','M','2011-10-24','Wanaka','Donec@dolorsitamet.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (72,'Hu Patton','M','1978-07-05','Nijlen','cursus@molestiearcuSed.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (73,'Jin Reilly','M','1980-09-02','Pointe-aux-Trembles','ornare.elit.elit@non.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (74,'Omar Gallagher','M','1969-12-06','Chapadinha','nibh.Phasellus.nulla@cursus.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (75,'Henry Powell','M','2006-04-18','Münster','ornare.tortor@rutrum.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (76,'Laith Sweeney','M','1971-11-05','Araban','Ut.tincidunt@nullaIntegervulputate.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (77,'Uriah Sanchez','M','2000-08-09','Florenville','risus@orciUt.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (78,'Victor Horne','M','2009-10-21','Nacimiento','montes.nascetur@idante.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (79,'Axel Hale','M','1976-10-27','Ruette','fringilla.ornare.placerat@gravidaAliquamtincidunt.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (80,'Guy Kennedy','M','1997-08-04','Grantham','egestas.Aliquam.nec@Nulla.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (81,'Axel Bridges','M','1989-09-14','Proddatur','nibh.vulputate@In.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (82,'Merritt Hampton','M','1963-12-25','Scarborough','quam@nonummyac.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (83,'Rooney Ward','M','1955-10-30','Diano Arentino','hendrerit.Donec@tinciduntorciquis.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (84,'Fletcher Fuller','M','2007-08-12','Marlborough','nec@Mauris.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (85,'Burton Lancaster','M','1972-07-04','Tilly','vel.venenatis@tellusid.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (86,'Deacon Salas','M','2011-08-15','Bensheim','lorem.ipsum.sodales@Fusce.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (87,'Matthew Garcia','M','2000-11-27','Bearberry','mus.Donec@IncondimentumDonec.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (88,'Justin Fitzgerald','M','1997-10-09','Llandrindod Wells','turpis@Nunc.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (89,'Wyatt Foster','M','2007-11-07','Inverness','ipsum@atpede.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (90,'Xander Bray','M','1951-09-25','Santo Stefano del Sole','natoque.penatibus.et@aliquamerosturpis.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (91,'Peter Barlow','M','2012-06-20','Sulzbach','diam.Sed@eteuismod.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (92,'Lewis Hensley','M','2015-05-22','Sneek','Mauris@consequat.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (93,'Griffin Bridges','M','1989-03-06','Saharanpur','sapien.Nunc@purus.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (94,'Ian Bullock','M','2003-07-01','Helensburgh','congue@semut.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (95,'Rashad Rowe','M','1971-09-15','Guarapuava','ac.mattis@nonleo.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (96,'Abel Keller','M','2010-07-31','Juneau','nisl.Quisque.fringilla@sapiencursus.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (97,'Conan Wilkerson','M','1982-07-22','Coupar Angus','orci.adipiscing@molestieorci.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (98,'Gareth Cook','M','1989-02-02','Bangor','Nunc.ac.sem@ut.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (99,'Ezra Dale','M','1996-10-09','Montgomery','metus.Aliquam@PhasellusornareFusce.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (100,'Nolan Keller','M','1957-07-05','Campinas','non.sapien@augue.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (101,'Brynn','F','1998-07-18','Münster','ac.eleifend@MaurisnullaInteger.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (102,'Chava','F','1950-04-05','Morwell','hendrerit@orci.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (103,'Zelda','F','2001-11-18','Deutschkreutz','mi.enim@quisturpisvitae.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (104,'Brynn','F','1958-11-19','Koningshooikt','magna.Suspendisse@antelectus.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (105,'Nina','F','1973-02-13','Heusden','tellus.sem.mollis@massalobortisultrices.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (106,'Jena','F','1978-01-31','Saintes','a.arcu@DonecestNunc.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (107,'Wynter','F','2013-09-05','Wilmont','ut.lacus@sagittissemper.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (108,'Victoria','F','1959-09-10','Höchst','Sed.id.risus@justo.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (109,'Jenna','F','1988-11-28','Warren','Mauris.eu@Maecenaslibero.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (110,'Bethany','F','2010-09-10','Castle Douglas','Ut.tincidunt.orci@eleifend.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (111,'Violet','F','1978-01-02','Metairie','in@egettinciduntdui.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (112,'Alisa','F','1983-03-09','Morgex','congue@Vivamus.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (113,'Shea','F','1957-10-09','Sherbrooke','mi@Vivamusmolestie.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (114,'Indira','F','2001-05-10','Parrano','Praesent@et.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (115,'Lydia','F','1972-03-21','Steenhuffel','Nunc.pulvinar@penatibuset.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (116,'Beatrice','F','1973-11-07','Bredene','Nunc.ac.sem@Pellentesquetincidunt.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (117,'Danielle','F','1956-12-25','Baileux','lorem@augueut.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (118,'Neve','F','1990-12-28','Radom','Vestibulum.ut@placerataugueSed.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (119,'Mariam','F','1983-10-25','Wyoming','Cum@metus.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (120,'Karen','F','1963-07-03','Kitchener','amet@sitamet.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (121,'Jaden','F','1954-09-06','Jette','porta.elit.a@Donecvitae.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (122,'Uma','F','1991-02-26','San Lazzaro di Savena','a@milacinia.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (123,'Florence','F','2004-10-20','Leersum','a.nunc@elit.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (124,'Lisandra','F','1965-09-25','Bhir','facilisis@Donecest.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (125,'Sybil','F','1955-06-02','Pitt Meadows','non.massa@disparturientmontes.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (126,'Ariana','F','1982-09-16','Jauche','sem@utodiovel.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (127,'Idona','F','1985-04-20','Koolkerke','purus.ac.tellus@lacus.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (128,'Kirsten','F','2013-07-22','Calder','dui.augue@egestasa.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (129,'Signe','F','1990-04-13','Chelmsford','gravida.Aliquam.tincidunt@senectuset.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (130,'Justina','F','1975-02-05','Fulda','odio@aliquet.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (131,'Maite','F','1961-02-03','Cerro Navia','quis.turpis.vitae@lacus.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (132,'Lois','F','1979-05-21','Rouen','nec.urna@Class.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (133,'Petra','F','1958-02-05','Eckville','tempus.lorem@etmagnis.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (134,'Meghan','F','1982-08-28','Rimouski','varius.et@Donecluctus.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (135,'Buffy','F','1986-07-10','Van','lorem.fringilla@quis.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (136,'Rana','F','1956-02-22','Ujjain','nonummy@nequeNullam.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (137,'Ariel','F','1978-03-16','Henderson','lorem.vitae@ideratEtiam.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (138,'Miriam','F','1986-10-11','Hantes-WihŽries','nascetur.ridiculus.mus@Maurismagna.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (139,'Gail','F','1960-12-11','Salamanca','nisi.Aenean.eget@vitaedolor.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (140,'Dominique','F','1985-09-06','Whitburn','semper.Nam.tempor@velitinaliquet.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (141,'Larissa','F','1971-05-14','Owensboro','Donec.porttitor@lorem.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (142,'Amethyst','F','1953-12-26','Kircudbright','Sed.nulla.ante@infelis.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (143,'Alyssa','F','2000-04-12','Merchtem','diam.Sed.diam@necmaurisblandit.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (144,'Imogene','F','2006-06-14','Redlands','Nam.tempor.diam@pharetraQuisqueac.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (145,'Xena','F','1987-02-12','Grande Prairie','consectetuer.adipiscing@amet.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (146,'Jana','F','1995-05-27','Flint','orci.tincidunt.adipiscing@duiCumsociis.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (147,'Illana','F','1993-05-27','Neuwied','est@eu.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (148,'Hayley','F','1961-03-20','Kakisa','purus.sapien.gravida@urnaconvallis.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (149,'Genevieve','F','1996-06-05','Blind River','id@tinciduntvehicula.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (150,'Leah','F','1989-11-24','Igboho','at@elitdictumeu.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (151,'Iris','F','1975-12-30','Cerrillos','felis.eget.varius@Maurisvel.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (152,'Ora','F','1991-07-19','Sooke','fermentum@eu.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (153,'Hyacinth','F','1960-10-20','Arrah','neque.sed.sem@Donecdignissimmagna.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (154,'Bertha','F','1983-05-09','Anzegem','a.auctor.non@malesuadamalesuada.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (155,'Allegra','F','1986-05-21','Sanluri','neque@Nullam.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (156,'Xantha','F','1983-01-20','Schepdaal','semper.dui.lectus@molestietellus.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (157,'Hannah','F','2001-10-25','Anantapur','libero.Proin@vitae.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (158,'Keely','F','1995-02-06','Capena','aptent@orciPhasellusdapibus.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (159,'Inez','F','1964-02-15','Innisfail','facilisis.lorem@eleifendvitae.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (160,'Cecilia','F','1969-12-17','Saint-Étienne-du-Rouvray','Quisque@atlacusQuisque.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (161,'Joy','F','1998-07-18','Pulle','blandit.enim.consequat@nisl.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (162,'Melanie','F','2016-06-10','Temploux','luctus.et@lacusNulla.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (163,'Pamela','F','1976-10-11','Rastatt','risus@et.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (164,'Lynn','F','1993-05-28','Mespelare','Suspendisse.non.leo@malesuadafringillaest.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (165,'Destiny','F','1985-06-05','Grand Rapids','tincidunt.nibh@ligulatortordictum.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (166,'Beatrice','F','2002-03-10','La Salle','arcu.Nunc.mauris@interdumCurabiturdictum.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (167,'Charity','F','1962-09-05','Hualpén','Mauris.vel.turpis@lacusQuisquepurus.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (168,'Chava','F','2006-06-18','Juneau','diam.nunc.ullamcorper@purusgravida.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (169,'Mona','F','1972-02-06','Birecik','cursus.diam.at@neceleifend.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (170,'Amethyst','F','2011-11-12','Rockford','eget.lacus@odio.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (171,'Germaine','F','2001-05-10','Sneek','Fusce.fermentum@nonvestibulum.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (172,'Dara','F','1966-04-21','Diepenbeek','posuere@dictumultricies.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (173,'Alea','F','1953-05-03','Middlesbrough','primis.in@pellentesqueafacilisis.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (174,'Fallon','F','1973-12-03','Grande Prairie','enim@cubiliaCuraePhasellus.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (175,'MacKenzie','F','2013-09-02','Krems an der Donau','ac.mattis.semper@atlibero.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (176,'Rae','F','1968-09-15','Dunoon','quis.tristique.ac@interdumligula.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (177,'Teegan','F','1968-10-21','Bonlez','molestie.tellus.Aenean@egestasblandit.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (178,'Eleanor','F','1984-02-05','Cassaro','sem@portaelit.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (179,'Cara','F','1952-01-12','Río Claro','justo.Proin@nisl.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (180,'Aiko','F','1959-12-14','Lampeter','augue.porttitor.interdum@estacfacilisis.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (181,'Idola','F','2011-05-02','Inuvik','sapien.Aenean.massa@orciquislectus.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (182,'Melissa','F','1951-01-26','Meux','sagittis@nec.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (183,'Lillian','F','1953-09-20','Caloundra','tristique@mauris.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (184,'Lavinia','F','1961-07-16','Venezia','lectus.pede.et@dictum.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (185,'Winifred','F','1968-05-05','Vaughan','fermentum@Mauris.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (186,'Mollie','F','1961-04-07','Fairbanks','Nulla.aliquet.Proin@commodoipsum.ca');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (187,'Quail','F','1984-08-18','Machalí','metus@AeneanmassaInteger.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (188,'Lenore','F','2005-05-03','Gresham','lobortis.nisi.nibh@risusvariusorci.co.uk');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (189,'Illana','F','1989-10-25','Thisnes','turpis@molestie.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (190,'Quintessa','F','1958-08-03','Alcobendas','vel.convallis.in@interdumligulaeu.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (191,'Avye','F','1963-03-08','Cardiff','non.feugiat.nec@Mauris.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (192,'Halla','F','1981-02-01','Clermont-Ferrand','laoreet.libero.et@tempus.com');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (193,'Tamekah','F','2000-03-31','Urbe','molestie.tortor@Fuscefermentumfermentum.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (194,'Amity','F','2005-05-19','Juazeiro','eget.laoreet@risusQuisquelibero.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (195,'Cathleen','F','1980-12-04','Yaxley','ultricies@magnaUt.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (196,'Chanda','F','1952-02-10','Freiburg','ut.ipsum@acurna.edu');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (197,'Casey','F','2003-01-26','Akşehir','placerat@eget.net');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (198,'Myra','F','1983-01-31','Viesville','Nulla.interdum.Curabitur@ac.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (199,'Velma','F','1998-10-23','Labrecque','elementum.sem.vitae@Inscelerisque.org');
INSERT INTO "cliente2" (idCliente,nomeCliente,sexo,dataNascimento,cidade,email) VALUES (200,'MacKensie','F','2008-06-10','Geleen','sit@leoelementumsem.net');

---criando a tabela cliente1
  
CREATE TABLE "cliente1" (
  codigoCliente int primary key ,
  nome varchar(50),
  sobrenome varchar(50),
  sexo varchar(10),
  dataNascimento date,
  cidade varchar(100),
  lugar varchar(100),
  email varchar(100),
  telefone varchar(10)
);

INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (30,'Harrison','Valencia','Masculino','1962-05-17','Diadema','São Paulo','sodales.at.velit@tinciduntadipiscing.org','19070-460');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (37,'Hop','Sharp','Masculino','1985-11-10','Parauapebas','Pará','quis.pede@In.edu','67478-005');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (44,'Marvin','Mcclain','Masculino','2008-05-15','Blumenau','Santa Catarina','quis.diam.Pellentesque@egestasSedpharetra.com','88539-080');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (51,'Amal','Sanchez','Masculino','1996-11-02','Niterói','Rio de Janeiro','erat@anteipsum.org','27683-719');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (58,'Ferris','Clemons','Masculino','1990-10-05','Rio Verde','Goiás','mauris.rhoncus.id@ligula.org','75713-718');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (65,'Tyrone','Sutton','Masculino','1999-06-24','Patos','Paraíba','amet.consectetuer@Sedauctor.edu','58088-620');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (72,'Kasimir','Norman','Masculino','1960-06-10','Ilhéus','Bahia','facilisis@pharetranibh.co.uk','40149-802');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (79,'Nash','Guy','Masculino','2010-03-08','Governador Valadares','Minas Gerais','et.tristique.pellentesque@Duis.org','32425451');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (86,'Abbot','Paul','Masculino','1962-11-07','Nova Iguaçu','Rio de Janeiro','Etiam.imperdiet.dictum@risusodioauctor.co.uk','27439-151');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (93,'Ciaran','Leonard','Masculino','2015-10-27','Cametá','Pará','Nulla.interdum.Curabitur@tortorNunc.org','66121-288');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (100,'Brent','Justice','Masculino','2010-05-13','Belém','Pará','vitae.aliquam@et.edu','66586-366');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (107,'Samuel','Roman','Masculino','2016-03-10','Paço do Lumiar','Maranhão','tincidunt@dictumPhasellus.edu','65998-846');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (114,'Vincent','Ewing','Masculino','1984-06-29','Mogi das Cruzes','São Paulo','egestas.ligula@Aeneaneget.com','18023-416');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (121,'Wade','Vargas','Masculino','1992-04-24','Mogi das Cruzes','São Paulo','nunc.Quisque.ornare@massaQuisqueporttitor.org','19194-783');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (128,'Steven','Blackburn','Masculino','2000-01-31','Osasco','São Paulo','egestas.Aliquam.fringilla@ornare.net','11438-864');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (135,'Deacon','Walsh','Masculino','1987-04-16','Campos dos Goytacazes','Rio de Janeiro','mus@ultricies.edu','24048-119');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (142,'Dalton','Hurley','Masculino','2008-07-04','Fortaleza','Ceará','Fusce.diam@risusDuisa.co.uk','60130-302');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (149,'Akeem','Barry','Masculino','2013-10-28','Pelotas','Rio Grande do Sul','Maecenas.ornare@mauriserat.ca','98992-120');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (156,'Colby','Pollard','Masculino','1988-05-19','São João de Meriti','Rio de Janeiro','Suspendisse@iaculisnec.co.uk','23976-869');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (163,'Kevin','Bauer','Masculino','1963-10-20','Belém','Pará','ac.feugiat@idrisus.edu','67720-982');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (170,'Alvin','Patton','Masculino','1978-10-27','Marabá','Pará','libero@egetipsumDonec.com','66526-000');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (177,'Jakeem','Nieves','Masculino','2002-05-11','Aparecida de Goiânia','Goiás','magna.Lorem@Donecluctus.org','74783-186');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (184,'Keane','Boyd','Masculino','1998-08-24','Mogi das Cruzes','São Paulo','ultrices@ipsumcursusvestibulum.net','14846-300');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (191,'Ross','Levy','Masculino','1978-07-17','Guarulhos','São Paulo','neque@acfacilisis.ca','14311-670');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (198,'Lars','Boyd','Masculino','1992-04-06','Nova Iguaçu','Rio de Janeiro','tellus@tristiquesenectus.net','20573-460');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (205,'Russell','Moran','Masculino','1980-08-21','Fortaleza','Ceará','Nam.consequat.dolor@lectuspede.co.uk','62202-277');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (212,'Joel','Petty','Masculino','2001-09-26','Sete Lagoas','Minas Gerais','lacus.varius.et@Loremipsumdolor.edu','30915588');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (219,'Wesley','Sykes','Masculino','1954-12-30','Diadema','São Paulo','ipsum.porta.elit@acturpisegestas.com','16533-969');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (226,'Walker','Crosby','Masculino','1994-12-06','Foz do Iguaçu','Paraná','nisl.sem.consequat@nullaInteger.edu','85165-072');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (233,'Phelan','Dalton','Masculino','1993-05-24','Diadema','São Paulo','ligula.eu.enim@nonjustoProin.org','16805-222');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (240,'Eaton','Le','Masculino','1961-03-18','Luziânia','Goiás','semper.erat@Sed.com','74747-617');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (247,'Omar','Calhoun','Masculino','2007-12-29','Ponta Grossa','Paraná','Sed.molestie@loremutaliquam.net','87640-851');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (254,'Kieran','Jenkins','Masculino','1962-02-18','Santa Luzia','Minas Gerais','iaculis.aliquet@enimdiamvel.ca','33158055');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (261,'Vernon','Spencer','Masculino','2004-03-21','Montes Claros','Minas Gerais','consectetuer.rhoncus.Nullam@lacusNullatincidunt.com','31663437');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (268,'Clinton','Norris','Masculino','1984-04-26','Camaragibe','Pernambuco','elit.sed.consequat@turpisvitaepurus.com','52358-615');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (275,'Clarke','Hodges','Masculino','2012-10-15','Belo Horizonte','Minas Gerais','sem.vitae.aliquam@Morbivehicula.ca','31394121');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (282,'Armand','Sosa','Masculino','1971-11-24','Carapicuíba','São Paulo','magna@et.ca','17897-842');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (289,'Lewis','Fox','Masculino','2003-10-06','Novo Hamburgo','Rio Grande do Sul','Pellentesque.tincidunt@nullaIntincidunt.edu','98330-436');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (296,'Brady','Valenzuela','Masculino','2015-12-04','Jundiaí','São Paulo','ultrices.Vivamus@consectetuer.com','18032-959');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (303,'Buckminster','Nielsen','Masculino','1981-01-06','Santa Maria','Rio Grande do Sul','In.faucibus@enim.org','94325-400');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (310,'Blaze','Rollins','Masculino','2008-08-12','Jaboatão dos Guararapes','Pernambuco','metus.Aliquam.erat@lacusvestibulumlorem.com','55938-209');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (317,'Basil','Hodges','Masculino','1992-09-28','Patos','Paraíba','arcu.Sed.eu@uteratSed.ca','58835-991');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (324,'Clarke','Gamble','Masculino','2010-04-21','São João de Meriti','Rio de Janeiro','elit.Nulla@Proinegetodio.com','26962-384');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (331,'Hilel','Ortega','Masculino','2017-08-19','Ilhéus','Bahia','bibendum.Donec.felis@elitAliquam.ca','42453-699');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (338,'Jasper','Wallace','Masculino','1998-08-29','Diadema','São Paulo','Mauris@purusinmolestie.co.uk','11158-432');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (345,'Tad','Myers','Masculino','1953-05-20','Campinas','São Paulo','tellus@orci.com','16882-708');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (352,'Fulton','Cross','Masculino','1959-08-02','Gravataí','Rio Grande do Sul','nunc.ullamcorper.eu@a.co.uk','96158-403');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (359,'Gannon','Drake','Masculino','1962-03-12','Caxias do Sul','Rio Grande do Sul','Donec.nibh.enim@nibhAliquamornare.net','98795-921');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (366,'Levi','Matthews','Masculino','1963-03-18','Caxias do Sul','Rio Grande do Sul','rutrum.non.hendrerit@blandit.ca','96685-419');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (373,'Donovan','Callahan','Masculino','1962-09-23','Contagem','Minas Gerais','Nulla@a.com','36257681');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (380,'Arden','Schroeder','Masculino','2004-04-27','Guarulhos','São Paulo','dictum.magna.Ut@Innec.edu','11603-157');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (387,'Emery','Wagner','Masculino','2008-04-13','Piracicaba','São Paulo','ac.mi.eleifend@etrutrumnon.ca','14675-075');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (394,'Jesse','Mcleod','Masculino','2011-10-15','Belo Horizonte','Minas Gerais','vehicula.aliquet@musProinvel.com','39839736');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (401,'Bevis','Wagner','Masculino','1957-06-07','Uberlândia','Minas Gerais','iaculis@tincidunt.org','39068250');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (408,'Stuart','Mason','Masculino','1980-11-25','Patos','Paraíba','ac.eleifend@augue.co.uk','58551-620');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (415,'Baker','Baxter','Masculino','1969-06-23','Guarulhos','São Paulo','Donec.dignissim@velitdui.edu','12794-626');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (422,'Cole','Bird','Masculino','1996-02-24','Parauapebas','Pará','sit.amet@Duisvolutpat.org','66440-520');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (429,'Quinlan','Howell','Masculino','1972-05-07','Piracicaba','São Paulo','ac.risus.Morbi@massa.ca','14390-762');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (436,'Hashim','Duncan','Masculino','1967-04-24','Belford Roxo','Rio de Janeiro','aptent.taciti@egestasAliquamnec.edu','20520-553');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (443,'Walker','Allison','Masculino','1988-04-05','Timon','Maranhão','varius.orci@Aeneangravida.net','65901-664');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (450,'Driscoll','Mendez','Masculino','1951-06-20','Luziânia','Goiás','sem@elit.co.uk','73712-548');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (457,'Kenneth','Lynch','Masculino','1972-06-30','Pelotas','Rio Grande do Sul','vitae.mauris.sit@Sedidrisus.ca','94976-590');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (464,'Rigel','Ingram','Masculino','1976-04-12','Diadema','São Paulo','orci.in@aliquetnec.net','12882-921');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (471,'Giacomo','Abbott','Masculino','1999-02-27','Ponta Grossa','Paraná','mus.Proin.vel@orciluctus.edu','83874-617');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (478,'Gray','Erickson','Masculino','2005-05-11','Petrópolis','Rio de Janeiro','ac.risus@Maurisblanditenim.com','27155-003');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (485,'Nasim','Griffin','Masculino','1977-09-25','Jundiaí','São Paulo','congue.In.scelerisque@sitametnulla.edu','16579-874');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (492,'Wesley','Olsen','Masculino','1992-03-09','Governador Valadares','Minas Gerais','nec.imperdiet@ornareegestas.net','30186890');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (499,'William','Sherman','Masculino','1999-07-10','Barra do Corda','Maranhão','luctus.et@a.edu','65985-945');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (506,'Lyle','Velasquez','Masculino','1999-09-30','Castanhal','Pará','commodo@feugiatnonlobortis.net','67573-745');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (513,'Russell','Klein','Masculino','1996-11-07','Diadema','São Paulo','ante.iaculis.nec@velnisl.ca','13031-180');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (520,'Fletcher','Garza','Masculino','1988-03-29','Cabo de Santo Agostinho','Pernambuco','mus.Donec.dignissim@orciadipiscingnon.co.uk','50207-828');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (527,'Quinn','Kirby','Masculino','2006-01-21','Camaragibe','Pernambuco','consequat.enim.diam@quisturpisvitae.co.uk','51358-433');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (534,'Elijah','Sutton','Masculino','1984-07-02','Camaçari','Bahia','vestibulum.lorem.sit@Phasellusnulla.com','44393-982');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (541,'Zeph','Glover','Masculino','1986-03-28','Belém','Pará','interdum.ligula.eu@tristiquepharetra.ca','66534-147');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (548,'Macon','Fletcher','Masculino','1986-06-11','São Gonçalo','Rio de Janeiro','lectus@elit.co.uk','27771-108');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (555,'Harlan','Ochoa','Masculino','2012-08-02','Belford Roxo','Rio de Janeiro','Nunc.pulvinar.arcu@vulputate.com','22005-252');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (562,'Boris','Trevino','Masculino','1972-06-07','Mogi das Cruzes','São Paulo','erat@sitamet.net','11465-363');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (569,'Uriel','Bender','Masculino','1986-09-24','Guarulhos','São Paulo','neque.vitae.semper@vitaeeratVivamus.com','16974-645');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (576,'Blake','Morton','Masculino','1991-07-18','Vitória da Conquista','Bahia','rutrum.magna@sagittisNullamvitae.ca','46264-909');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (583,'Gage','Gilbert','Masculino','1997-07-02','Campos dos Goytacazes','Rio de Janeiro','odio@sollicitudin.org','20981-415');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (590,'Xanthus','Kemp','Masculino','1982-05-20','Caxias do Sul','Rio Grande do Sul','ridiculus.mus@necleo.co.uk','97651-036');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (597,'Gage','Golden','Masculino','1974-09-09','Piracicaba','São Paulo','posuere.vulputate@sagittisDuisgravida.org','15189-272');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (604,'Caldwell','Puckett','Masculino','2008-07-23','Barra do Corda','Maranhão','nec@Namnullamagna.edu','65334-563');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (611,'Nehru','Aguilar','Masculino','1979-04-22','Jaboatão dos Guararapes','Pernambuco','ullamcorper@imperdietdictum.edu','51915-865');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (618,'Benedict','Casey','Masculino','1976-07-18','Salvador','Bahia','eu.enim@elitafeugiat.ca','46109-441');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (625,'Dieter','Vinson','Masculino','1987-06-08','Diadema','São Paulo','egestas.ligula@Curabitur.com','15870-090');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (632,'Troy','Wilkins','Masculino','1967-01-03','Piracicaba','São Paulo','neque.sed.sem@volutpat.edu','16886-875');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (639,'Ryder','Mcmahon','Masculino','1978-01-11','Paulista','Pernambuco','lorem.eget@tempuslorem.edu','56009-478');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (646,'Hakeem','Richards','Masculino','1974-09-07','Foz do Iguaçu','Paraná','libero.at@miacmattis.org','83978-593');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (653,'Oliver','Cabrera','Masculino','1985-12-09','Nova Iguaçu','Rio de Janeiro','ornare.facilisis@fringillaestMauris.ca','25213-113');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (660,'Cullen','Morin','Masculino','1951-02-11','Juazeiro do Norte','Ceará','luctus.aliquet.odio@imperdiet.co.uk','63642-378');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (667,'Gage','Noble','Masculino','1961-10-02','Mogi das Cruzes','São Paulo','interdum@egestashendreritneque.edu','18606-189');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (674,'Malachi','Small','Masculino','1985-06-07','São Gonçalo','Rio de Janeiro','ac@et.com','24559-929');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (681,'Preston','Battle','Masculino','1981-12-05','Juiz de Fora','Minas Gerais','non.dui.nec@velarcueu.com','35573239');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (688,'Fulton','Shannon','Masculino','1984-08-03','Cabo de Santo Agostinho','Pernambuco','consectetuer.rhoncus.Nullam@vestibulumlorem.com','56175-464');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (695,'Caesar','Harrington','Masculino','2000-10-30','Petrópolis','Rio de Janeiro','fermentum@facilisisegetipsum.com','22213-790');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (702,'Talon','Haney','Masculino','1982-05-10','Campinas','São Paulo','Nullam@Vivamusnisi.edu','18935-603');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (709,'Bradley','Mcgee','Masculino','2010-06-19','Chapecó','Santa Catarina','ligula.Aenean@est.ca','88155-454');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (716,'Zahir','Hammond','Masculino','1959-08-08','Ribeirão Preto','São Paulo','In.nec@ante.org','12604-988');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (723,'Donovan','Black','Masculino','1972-10-19','Maranguape','Ceará','nascetur.ridiculus.mus@ametconsectetueradipiscing.net','61266-465');

INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (722,'Rylee','Nolan','Feminino','1955-09-21','Crato','Ceará','rutrum.urna@nuncullamcorpereu.ca','62728-436');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (724,'Kevyn','Barker','Feminino','1970-05-15','Caxias do Sul','Rio Grande do Sul','odio@hendrerit.com','94632-228');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (725,'Kai','Allison','Feminino','2011-10-01','Mogi das Cruzes','São Paulo','commodo.auctor@lobortisClassaptent.co.uk','19898-665');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (726,'Tana','Fitzgerald','Feminino','1987-12-03','Cascavel','Paraná','eleifend@nisimagnased.ca','85378-526');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (727,'Ima','Santos','Feminino','1976-07-15','São Gonçalo','Rio de Janeiro','dis@elitfermentumrisus.edu','22891-353');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (728,'Piper','Swanson','Feminino','2009-09-24','Jundiaí','São Paulo','neque.non@ornare.net','11661-758');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (729,'Hedy','Vaughan','Feminino','1980-09-23','Lauro de Freitas','Bahia','Nunc.mauris@euarcuMorbi.edu','40618-228');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (730,'Hope','Rocha','Feminino','1955-10-13','Santa Rita','Paraíba','magna@lectusrutrum.ca','58549-887');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (731,'Kaitlin','Davis','Feminino','1994-07-05','Ponta Grossa','Paraná','dolor@iaculisodio.org','87606-076');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (732,'Irma','Savage','Feminino','1994-06-24','Contagem','Minas Gerais','sagittis@luctus.com','38488434');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (733,'Skyler','Stokes','Feminino','1981-05-30','Mauá','São Paulo','risus.In.mi@Quisquepurus.ca','18225-987');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (734,'Sylvia','French','Feminino','1985-12-22','João Pessoa','Paraíba','et@Sed.ca','58137-107');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (735,'Nita','Schmidt','Feminino','2006-01-15','Mogi das Cruzes','São Paulo','tellus@varius.org','18169-949');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (736,'Gwendolyn','Sanchez','Feminino','1961-04-18','Olinda','Pernambuco','Cras@posuere.net','54054-549');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (737,'Charissa','Brennan','Feminino','2008-09-21','Juiz de Fora','Minas Gerais','nunc.In@Integeraliquam.ca','34738570');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (738,'Shafira','Herrera','Feminino','1950-07-20','Canoas','Rio Grande do Sul','vitae@Nulla.edu','94279-555');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (739,'Michelle','Downs','Feminino','2008-07-13','João Pessoa','Paraíba','non.hendrerit.id@neque.net','58279-241');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (740,'Deirdre','Jefferson','Feminino','1950-10-26','Santa Maria','Rio Grande do Sul','convallis@Cras.net','90332-811');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (741,'Kiara','Munoz','Feminino','2000-09-02','Cabo de Santo Agostinho','Pernambuco','magnis.dis.parturient@Morbi.com','56234-096');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (742,'Jaquelyn','Mason','Feminino','1979-09-24','Petrolina','Pernambuco','Suspendisse.tristique@tellusimperdietnon.edu','53312-652');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (743,'Pamela','Pate','Feminino','2017-03-28','Piracicaba','São Paulo','convallis@Sedid.edu','19200-592');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (744,'Stacy','Arnold','Feminino','1953-09-15','Pelotas','Rio Grande do Sul','Nullam@magna.co.uk','94842-390');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (745,'Jenna','Gentry','Feminino','1963-05-30','Contagem','Minas Gerais','aliquet.vel@placerat.org','35179375');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (746,'Anjolie','Malone','Feminino','1960-09-01','Camaragibe','Pernambuco','augue.ac.ipsum@vitae.ca','51501-164');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (747,'Sade','Watts','Feminino','1954-05-07','Ribeirão Preto','São Paulo','tristique.senectus.et@euelitNulla.co.uk','18795-465');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (748,'Yetta','Logan','Feminino','1950-04-10','Paço do Lumiar','Maranhão','Mauris@dolor.co.uk','65272-109');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (749,'Maile','Kidd','Feminino','1952-07-21','Juazeiro do Norte','Ceará','mauris.Morbi@Duis.co.uk','60551-796');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (750,'Emi','Perez','Feminino','1965-10-02','Ribeirão das Neves','Minas Gerais','purus.Duis.elementum@tristiquesenectus.edu','38081438');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (751,'Ainsley','Mcfadden','Feminino','1985-12-02','Jundiaí','São Paulo','auctor@feugiattelluslorem.edu','13430-090');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (752,'Nomlanga','Greene','Feminino','1961-12-18','Campinas','São Paulo','montes.nascetur.ridiculus@tempusrisusDonec.org','16683-575');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (753,'Paloma','Floyd','Feminino','2000-05-30','Guarulhos','São Paulo','erat.in@ac.net','13286-523');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (754,'Ginger','Wright','Feminino','2002-08-04','Juazeiro','Bahia','faucibus@non.net','41527-523');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (755,'Martina','Lucas','Feminino','1982-12-09','Campos dos Goytacazes','Rio de Janeiro','risus.a.ultricies@cursusinhendrerit.com','25201-450');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (756,'Ainsley','Boyer','Feminino','2007-01-20','Luziânia','Goiás','dui.Fusce.diam@faucibusid.co.uk','76728-897');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (757,'Sopoline','Wise','Feminino','2004-11-23','Guarulhos','São Paulo','Aliquam@uterat.edu','13158-498');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (758,'Cathleen','Adkins','Feminino','2018-08-04','Ilhéus','Bahia','ut.nulla.Cras@at.edu','47134-432');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (759,'Lesley','Benton','Feminino','1993-04-01','Canoas','Rio Grande do Sul','erat@Namconsequatdolor.co.uk','90141-959');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (760,'Shay','Hardin','Feminino','1992-05-19','Blumenau','Santa Catarina','mi.eleifend.egestas@ametmetus.com','88199-650');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (761,'Galena','Gibbs','Feminino','2001-02-06','Guarapuava','Paraná','dui.nec@Curae.co.uk','83426-206');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (762,'Ursula','Mcdaniel','Feminino','2004-01-27','Juazeiro','Bahia','enim.Mauris@SuspendisseeleifendCras.com','42106-084');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (763,'Susan','Spears','Feminino','1956-01-31','Vitória da Conquista','Bahia','feugiat@accumsansed.edu','44993-155');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (764,'Scarlet','Duffy','Feminino','2005-11-11','Belford Roxo','Rio de Janeiro','molestie.dapibus@maurisanunc.org','27237-721');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (765,'Lani','Leon','Feminino','1997-06-13','Guarulhos','São Paulo','in.magna.Phasellus@odioapurus.net','15631-454');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (766,'Gretchen','Rose','Feminino','1982-01-04','Timon','Maranhão','Aliquam@laoreet.edu','65700-953');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (767,'Mechelle','Burns','Feminino','1996-10-05','Camaragibe','Pernambuco','gravida.sit.amet@velarcu.edu','51425-850');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (768,'Shellie','Cooke','Feminino','1961-08-02','Rio Grande','Rio Grande do Sul','tellus.Phasellus@Nullamfeugiat.edu','98770-201');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (769,'Rina','Justice','Feminino','2004-12-27','Niterói','Rio de Janeiro','mollis.Phasellus@enim.edu','22272-224');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (770,'Summer','Nguyen','Feminino','2000-03-02','Pelotas','Rio Grande do Sul','vulputate.lacus@diam.edu','98245-383');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (771,'Jasmine','Briggs','Feminino','1981-08-29','Osasco','São Paulo','velit@auctorodio.net','11372-354');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (772,'Rachel','Bernard','Feminino','2005-04-26','Santarém','Pará','pretium@laoreet.com','66067-249');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (773,'Darryl','Becker','Feminino','1968-06-26','Governador Valadares','Minas Gerais','lacus.Ut.nec@maurisipsum.co.uk','37517844');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (774,'Gloria','Lara','Feminino','1996-11-12','Duque de Caxias','Rio de Janeiro','est.congue@mi.edu','21076-990');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (775,'Moana','Tate','Feminino','1967-01-04','Juazeiro do Norte','Ceará','orci.Ut@NullamnislMaecenas.edu','62273-425');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (776,'Vanna','Gill','Feminino','1952-08-21','Campos dos Goytacazes','Rio de Janeiro','primis.in.faucibus@ullamcorpernisl.org','23900-930');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (777,'Olympia','Aguilar','Feminino','1963-03-21','Duque de Caxias','Rio de Janeiro','ac.turpis.egestas@congue.co.uk','23578-354');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (778,'Aimee','Hunter','Feminino','1990-03-07','Mogi das Cruzes','São Paulo','aliquet.lobortis@laciniaorciconsectetuer.ca','17274-235');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (779,'Lois','Lancaster','Feminino','1989-04-07','Jundiaí','São Paulo','magna.Duis@sedfacilisis.org','12047-917');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (780,'Inez','Goodwin','Feminino','2013-03-26','Santa Maria','Rio Grande do Sul','auctor@risusQuisquelibero.com','93797-019');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (781,'Faith','Castillo','Feminino','1976-12-06','Aparecida de Goiânia','Goiás','tellus@euismod.co.uk','74708-309');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (782,'Hollee','Beard','Feminino','1985-01-17','Porto Alegre','Rio Grande do Sul','dolor.sit@Crassed.co.uk','99686-878');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (783,'Martena','Ellison','Feminino','1977-09-04','Rio de Janeiro','Rio de Janeiro','Praesent@etmagna.co.uk','22981-420');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (784,'Jena','Diaz','Feminino','1986-05-23','Belém','Pará','egestas.nunc@Utnec.co.uk','68252-524');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (785,'Noelle','Randolph','Feminino','1994-08-14','Feira de Santana','Bahia','a@Crasinterdum.com','47364-714');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (786,'Ashely','Pollard','Feminino','1968-08-07','Sobral','Ceará','justo@consequatauctor.co.uk','63834-881');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (787,'Keely','Hale','Feminino','1991-09-25','São João de Meriti','Rio de Janeiro','nulla.In@euismodenim.ca','20433-666');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (788,'Victoria','Carney','Feminino','2013-04-11','Porto Alegre','Rio Grande do Sul','auctor@ornare.net','95359-963');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (789,'Elaine','Maxwell','Feminino','2000-06-10','Vitória da Conquista','Bahia','consectetuer.adipiscing.elit@vulputatenisi.edu','44935-687');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (790,'Janna','Mathews','Feminino','2001-07-04','Contagem','Minas Gerais','blandit.Nam@mi.edu','35874436');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (791,'Jaime','Dickson','Feminino','1975-05-21','Osasco','São Paulo','facilisis.lorem.tristique@quam.ca','11820-131');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (792,'Nyssa','Copeland','Feminino','2016-10-28','São Luís','Maranhão','urna@aliquet.com','65027-226');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (793,'Mariam','Dotson','Feminino','1954-10-02','Novo Hamburgo','Rio Grande do Sul','fringilla.mi@volutpat.co.uk','90391-502');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (794,'Ginger','Powers','Feminino','2008-08-05','Florianópolis','Santa Catarina','ipsum.Suspendisse.non@egestas.edu','89915-588');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (795,'Gillian','Goodwin','Feminino','1966-12-29','Salvador','Bahia','luctus.sit@dis.edu','41405-329');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (796,'Hyacinth','Koch','Feminino','1995-04-03','Cametá','Pará','at@blanditcongue.co.uk','68805-713');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (797,'Maite','Michael','Feminino','1953-07-13','Patos','Paraíba','dui@euodio.com','58008-868');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (798,'Paula','Pollard','Feminino','1957-01-14','Sobral','Ceará','Morbi.vehicula.Pellentesque@dolornonummy.edu','60815-899');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (799,'Bryar','Cook','Feminino','1967-04-03','Pelotas','Rio Grande do Sul','quis@metusIn.com','97386-375');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (800,'Kevyn','Jenkins','Feminino','1999-06-09','Paranaguá','Paraná','nisl.sem.consequat@aliquetsem.edu','85313-160');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (801,'Ursula','Hickman','Feminino','1966-03-12','Carapicuíba','São Paulo','Morbi.vehicula@egestasSedpharetra.co.uk','18402-212');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (802,'Catherine','Rivers','Feminino','2009-07-11','Carapicuíba','São Paulo','sem.eget@posuerecubiliaCurae.com','17958-959');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (803,'Melanie','Wiggins','Feminino','1993-09-29','Guarapuava','Paraná','erat.volutpat.Nulla@tinciduntnequevitae.ca','80416-992');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (804,'Cara','Mcleod','Feminino','2005-06-01','Blumenau','Santa Catarina','neque.sed@tortorNunc.org','89077-404');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (805,'Montana','Raymond','Feminino','2003-05-30','Piracicaba','São Paulo','ultrices@egestasblanditNam.ca','13668-170');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (806,'April','Vazquez','Feminino','1967-10-16','Sobral','Ceará','molestie@nonummyutmolestie.org','61028-014');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (807,'Jordan','Weaver','Feminino','1969-12-08','Florianópolis','Santa Catarina','Aenean@ametconsectetueradipiscing.net','88831-592');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (808,'Melyssa','Sheppard','Feminino','1951-11-14','Osasco','São Paulo','fringilla.est@lacusQuisqueimperdiet.ca','17479-772');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (809,'Uta','Pearson','Feminino','2002-07-11','Diadema','São Paulo','Etiam.vestibulum@pedeet.co.uk','11810-176');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (810,'Charissa','Curry','Feminino','1988-05-19','Duque de Caxias','Rio de Janeiro','luctus@porttitorvulputateposuere.net','22168-913');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (811,'Jada','Whitehead','Feminino','1988-10-11','Mauá','São Paulo','lorem.auctor.quis@estvitae.edu','15717-895');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (812,'Barbara','Copeland','Feminino','1955-09-22','Caucaia','Ceará','ut.aliquam@arcuac.edu','61788-822');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (813,'Maite','Dyer','Feminino','2003-12-19','Piracicaba','São Paulo','ullamcorper.viverra.Maecenas@id.edu','13263-229');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (814,'Bo','Rush','Feminino','2018-08-31','Águas Lindas de Goiás','Goiás','amet@imperdietnonvestibulum.ca','75776-050');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (815,'Shoshana','Cain','Feminino','1966-01-20','Piracicaba','São Paulo','Duis.volutpat@Nullamvitaediam.org','14339-157');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (816,'Xyla','Bauer','Feminino','1965-09-27','Balsas','Maranhão','turpis.non@gravidamolestiearcu.com','65962-830');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (817,'Quyn','Robertson','Feminino','1966-12-07','Canoas','Rio Grande do Sul','purus@lacusNullatincidunt.com','91657-672');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (818,'Xantha','Williams','Feminino','1997-08-29','Goiânia','Goiás','Ut.sagittis@faucibusorciluctus.com','74709-213');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (819,'Irma','Spencer','Feminino','1956-08-26','Maringá','Paraná','mi.felis@CuraePhasellus.co.uk','87809-803');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (820,'Zephr','Mcgee','Feminino','1953-09-21','Vitória da Conquista','Bahia','in@urnaconvallis.net','44050-391');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (821,'Fay','Galloway','Feminino','2016-08-26','Sete Lagoas','Minas Gerais','tortor.nibh.sit@lacus.co.uk','38105910');
INSERT INTO "cliente1" (codigoCliente,nome,sobrenome,sexo,dataNascimento,cidade,lugar,email,telefone) VALUES (822,'Cassandra','Baxter','Feminino','1976-10-23','Cabo de Santo Agostinho','Pernambuco','malesuada@idlibero.org','50737-020');

SELECT *
  FROM cliente1;
  
SELECT *
  FROM cliente2;  
    