-- MySQL Script generated by MySQL Workbench
-- Thu May 28 16:43:36 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema igtidb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema igtidb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `igtidb` DEFAULT CHARACTER SET utf8 ;
USE `igtidb` ;

-- -----------------------------------------------------
-- Table `igtidb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `igtidb`.`Funcionario` (
  `id_func` INT(11) NOT NULL,
  `nome_func` VARCHAR(255) NOT NULL,
  `nascimento` DATE NOT NULL,
  `salario` DECIMAL(10,2) NULL,
  `depto` INT(11) NOT NULL,
  PRIMARY KEY (`id_func`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `igtidb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `igtidb`.`Departamento` (
  `cod_depto` INT(11) NOT NULL,
  `nome_depto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_depto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
